server {
    listen 80;
    server_name apoyavenezuela.com;
    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ /router.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    }
}
